name: Check
on:
  push:
    branches:
    - main
    - workflow_check
  pull_request:
    branches:
    - main

env:
  # Emit backtraces on panics.
  RUST_BACKTRACE: full
  # Use sparse index (if supported).
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Sync toolchain
        shell: bash
        run: rustup show

      - name: Run cargo fmt
        shell: bash
        run: cargo fmt -- --check

      - name: Run cargo check
        shell: bash
        run: cargo check --workspace

      - name: Run cargo test
        shell: bash
        run: cargo test --workspace --no-fail-fast

      - name: Run cargo clippy
        shell: bash
        run: cargo clippy

      - name: Run cargo build
        shell: bash
        run: cargo build --verbose
