name: Check
on:
  push:
    branches:
    - main
    - workflow_check
  pull_request:
    branches:
    - main

env:
  # Emit backtraces on panics.
  RUST_BACKTRACE: full
  # Enable colors in cargo output.
  CARGO_TERM_COLOR: always
  # Use sparse index if supported - unlikely with the MSRV?
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Sync toolchain
        shell: bash
        run: rustup show

      - name: Run cargo fmt
        shell: bash
        run: cargo fmt -- --check

      - name: Run cargo check
        shell: bash
        run: RUSTFLAGS="-D warnings" cargo check --workspace

      - name: Run cargo test
        shell: bash
        run: cargo test --workspace --no-fail-fast

      - name: Run cargo examples
        shell: bash
        run: cargo run --example english

      - name: Run cargo clippy
        shell: bash
        run: cargo clippy
